# .github/workflows/development.yml
name: Development pipeline

on:
  push:

env:
  PYTHON_M: python -m

jobs:
  create-virtualenv:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

  school_lint:
    runs-on: ubuntu-22.04
    needs: create-virtualenv

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Install requirements-dev
        run: pip install -r requirements-dev.txt

      - name: Run Flake8
        run: |
          $PYTHON_M flake8 ft_dslr --disable-noqa --config setup.cfg

  projet_lint:
    runs-on: ubuntu-20.04
    needs: school_lint

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Install requirements-dev
        run: pip install -r requirements-dev.txt

      - name: Run make lint
        run: make lint
